### ISSUE TITLE
Application does not terminate

### ISSUE THREAD

**Issue by 239** [flathub/chat.simplex.simplex#2]
Instances keep running after closing the application: `flatpak ps`
```
Instance   PID   Application          Runtime
178348822  6108  org.mozilla.firefox  org.freedesktop.Platform
1972543518 11507 chat.simplex.simplex org.freedesktop.Platform
3130099956 11917 chat.simplex.simplex org.freedesktop.Platform
2858080772 12271 chat.simplex.simplex org.freedesktop.Platform
```

**Comment by shumvgolove** [comment]
Hmm, good catch. I'll investigate.

**Comment by shumvgolove** [comment]
It seems that inside sandbox spawns another process called `gsettings monitor org.gnome.desktop.interface gtk-theme` that monitors and applies gtk-theme dynamically from host changes. The weird thing is: it persists when `simplex` process exits.

I'll create a workaround that kills gsettings, should resolve the issue.
